version: '3.8'

services:
  # Dịch vụ Cơ sở dữ liệu quan hệ (PostgreSQL)
  postgres:
    image: postgres:16-alpine
    container_name: recruitment_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: smart_user
      POSTGRES_PASSWORD: smart_password
      POSTGRES_DB: smart_recruitment
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Dịch vụ Hàng đợi & Cache (Redis)
  redis:
    image: redis:7-alpine
    container_name: recruitment_redis
    ports:
      - "6379:6379"

  # Dịch vụ Cơ sở dữ liệu Vector (Qdrant)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: recruitment_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrantdata:/qdrant/storage

# Cấu hình Lưu trữ dữ liệu bền vững (Không bị mất data khi tắt Docker)
volumes:
  pgdata:
  qdrantdata: